apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongdb
  labels:
    apps: mongdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongdb
  template:
    metadata:
      labels:
        app: mongdb
    spec:
      containers:
      - name: mongdb
        image: mongodb
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: klestis-secrets
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: klestis-secrets
              key: password
